### ISSUE TITLE
Meta field in TwirpError should be initialised to empty Map

### ISSUE THREAD

**Issue by sobelek** [twirphp/twirp#158]
### Preflight Checklist

- [X] I have searched the [issue tracker](https://www.github.com/twirphp/twirp/issues) for an issue that matches the one I want to file, without success.
- [X] I am not looking for support or already pursued the available [support channels](https://github.com/twirphp/twirp/blob/master/.github/SUPPORT.md) without success.

### Version

0375522

### PHP version

8.0

### Expected Behavior

`meta` field of TwirpError should be initialised as empty Map or other PHP equivalent object.

### Actual Behavior

`meta` field of TwirpError gets initialised as empty list which causes deserialization error in clients. In my case it's java client.
It is happening here: https://github.com/twirphp/twirp/blob/0375522bc04167ec00622cbf65a96caded9ab23e/protoc-gen-twirp_php/templates/global/TwirpError.php.tmpl#L24

### Additional Information

Given the [spec](https://twitchtv.github.io/twirp/docs/errors.html), meta key should be an optional key => value string pairs. It doesn't mention an empty [] array
```
meta: (optional) key-value pairs with arbitrary string metadata. Useful to define subtypes under the same code, or add extra fields for the callers.
````

**Comment by sagikazarmark** [comment]
Hey @sobelek !

In PHP there is no dedicated map type to my knowledge. But I may have a solution.

Does it occur with both JSON and protobuf?

**Comment by sobelek** [comment]
@sagikazarmark Hey. Please forgive my ignorance but I have zero knowlage about PHP. Quick google proposes maybe just empty php object like: `(object) []`

Haven't tested protobuf. My case is with JSON

**Comment by sobelek** [comment]
yes. I will give it a try and report!

**Comment by sagikazarmark** [comment]
@sobelek I can upload a binary here if you tell me what platform should I target

**Comment by sobelek** [comment]
@sagikazarmark Hey. Turns out we don't have a simple way to test it in our pipeline.
But Looking at your PR there is an agreement that it looks good to go 👍

**Comment by sagikazarmark** [comment]
v0.11.0 should be up with the fix
