### ISSUE TITLE
Add JSON support to client

### ISSUE THREAD

**Issue by rastislavnemec** [twirphp/twirp#37]
I've encountered a problem with fixed content type in client.

Could we add support for JSON communication like the original library does and make type (Protobuf / JSON) optionable?

This would open the doors to better testability (widely used JSON mocks, handy structuring of expected data).

**Comment by sagikazarmark** [comment]
@rastislavnemec sorry, I've missed your issue.

I'm looking at the original code, but the way the generated client works (separate client for Protobuf and JSON) is not really PHPish.

What do you think about a named constructor? The default would continue to use protobuf, `*Client::newJson(...)` would return a client with JSON encoding.

Would that work for you?

**Comment by rastislavnemec** [comment]
Sure, with solution you proposed, it would.
