### ISSUE TITLE
Is it possible to use with laravel?

### ISSUE THREAD

**Issue by codeitlikemiley** [twirphp/twirp#38]
Im currently needing a client to send and received request from an api endpoint serve by a third party using protobuf message.

Is is possible to use with another framework like laravel?
If yes can you show me or pinpoint me to the right direction thanks

**Comment by sagikazarmark** [comment]
Well, this framework generates PSR-7 and PSR-17 compatible code, so if those works with Laravel, TwirPHP should too.

Note that this is an RPC framework, so you probably can't use only the client part. You need a server side counterpart that implements the same Twirp protocol.

**Comment by codeitlikemiley** [comment]
So it means not unless the backend service uses twirp then I can use this
for my client?
If not then this is not usable for me?
Correct...

**Comment by sagikazarmark** [comment]
I'm afraid that is correct.

**Comment by codeitlikemiley** [comment]
Well that is good to know, thank you for replying so quickly
