### ISSUE TITLE
Generating message DTO's with all properties required in constructor

### ISSUE THREAD

**Issue by the-toster** [twirphp/twirp#68]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I able to create invalid object by constructor

**Describe the solution you'd like**
All properties of message are required during new instance creating

**Describe alternatives you've considered**
Generate factory methods with app fields required, generate subclasses of messages with wanted behavior

**Additional context**
I understand that empty constructor is a php protoc plugin behavior, and it's right from protobuf v3 point of view (all fields are optional).  
But, assuming protobuf as transport layer, shouldn't we made this strict on application layer?  
It will requre extra (optional) generation step.  
I'll be glad to provide PR for this.

Possible this should be done completely separate from `twirphp`, as it only depends on php protobuf plugin.

Thank you for this great project!

**Comment by sagikazarmark** [comment]
@the-toster as you said, this is out of our hands as the message classes are generated by protoc.

> Thank you for this great project!

Cheers!
